var n = 8;
console.log("tabuada do número " +n);
console.log( n + " " + "x 0 = " + (n * 0));
console.log( n + " " + "x 1 = " + (n * 1));
console.log( n + " " + "x 2 = " + (n * 2));
console.log( n + " " + "x 3 = " + (n * 3));
console.log( n + " " + "x 4 = " + (n * 4));
console.log( n + " " + "x 5 = " + (n * 5));
console.log( n + " " + "x 6 = " + (n * 6));
console.log( n + " " + "x 7 = " + (n * 7));
console.log( n + " " + "x 8 = " + (n * 8));
console.log( n + " " + "x 9 = " + (n * 9));
console.log( n + " " + "x 10 = " + (n * 10));